### ISSUE TITLE
Icon format has not all the same size standard

### ISSUE THREAD

**Issue by SamuelCharest** [gsoft-inc/ov-igloo-icons#17]
Somes icon doesn't have the correct size.

For example Delete icon is 24x25 instead of 24x24
![image](https://user-images.githubusercontent.com/11981907/133287415-797947c6-0b5a-4f84-8424-92cf84396282.png)

Same for the Engagement icon
![image](https://user-images.githubusercontent.com/11981907/133287543-dbbc76f2-7cbc-4b32-a368-1e93efdab064.png)

**Comment by franckgaudin** [comment]
A validation of the size has been added to the build script.
